### ISSUE TITLE
Unable to install on R version 3.6.3

### ISSUE THREAD

**Issue by calebrottman** [psychmeta/psychmeta#113]
I tried installing psychmeta on R 3.6.3 (on Ubuntu 20.04) and the installation failed:

```
Installing package into ‘/home/crottman/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)

Warning message:
“dependency ‘metafor’ is not available”
Warning message in install.packages("psychmeta"):
“installation of package ‘psychmeta’ had non-zero exit status”
```

However, when I upgraded R to 4.2.1, everything worked fine.  The documentation says that psychmeta should work for >=3.5.0 (https://cran.r-project.org/web/packages/psychmeta/index.html), so you may just want to update that documentation.

**Comment by bwiernik** [comment]
Thanks. @jadahlke @wesley4546 The issue is importing metafor. We should move metafor to Suggests and make functions that depend on it check for installation before running.
