### ISSUE TITLE
Typo in .plot_forest results in accidental recycling

### ISSUE THREAD

**Issue by swnydick** [psychmeta/psychmeta#117]
I found odd results when I had moderator variables (CI lower bound greater than 0 but set to -1 for the plot). I think it's due to this in the `.plot_forest` internal function:

```r
plot_dat$upperci[dat$upperci > max(x_limits)] <- max(x_limits)
plot_dat$lowerci[dat$lowerci < min(x_limits)] <- min(x_limits)
```

If `plot_dat` and `dat` are of different sizes (which will happen if there are moderators), then it will accidentally recycle the lower and upper confidence interval limits. I think it should be:

```r
plot_dat$upperci[plot_dat$upperci > max(x_limits)] <- max(x_limits)
plot_dat$lowerci[plot_dat$lowerci < min(x_limits)] <- min(x_limits)
```

OR better yet as the package already depends on `dplyr`!

```r
plot_dat <- dplyr::mutate(plot_dat,
  upperci = pmin(upperci, max(x_limits)),
  lowerci = pmax(lowerci, min(x_limits)
)
```

**Comment by jadahlke** [comment]
Could you please supply a reproducible example illustrating the problem?

**Comment by jadahlke** [comment]
This has been fixed in the development build. Sorry for the _very_ long delay, I don't get much time to work on the package these days.
