### ISSUE TITLE
Can not reproduce correction for group misclassification

### ISSUE THREAD

**Issue by MatthewBJane** [psychmeta/psychmeta#118]
I am having a bit of trouble reproducing the correction for group misclassification. In the simple example below (where the only artifact present is misclassification) `correct_d` returns corrected d = .738 and doing it by hand returns corrected d = .790. I double checked my code and tried to read through the source code for `correct_d`, but I am still unsure why there is a discrepancy. This may be just a silly mistake on my part, but wanted to check! Thanks!

```
d_obs = .50
rGg = .70
nA = 40
nB = 60
p = nA / (nA + nB)

## correct with psychmeta
correct_d(d = d_obs,
          rGg = rGg,
          correction = "meas",
          pi = p,
          pa = p,
          n1 = nA,
          n2 = nB,
          correct_bias = FALSE)

## correct by hand
#  convert d to r
r = d_obs / sqrt( 1/(p*(1-p)) - d^2)

# correct r
rho = r / rGg

# convert r to d
delta = rho / sqrt( p*(1-p)*(1-rho^2) )

# print results
print(delta)
```

**Comment by MatthewBJane** [comment]
I found the issue. It was my mistake!

**Comment by bwiernik** [comment]
Glad you found it! Could you let me know the mistake so I can keep it in mind in the future?

**Comment by MatthewBJane** [comment]
It was a silly mistake. I just flipped the signs in the denominator for converting from *d* to *r*:

I had written:
```
#  convert d to r
r = d / sqrt( 1/(p*(1-p)) - d^2)
```

But it should have been: 

```
#  convert d to r
r = d / sqrt( 1/(p*(1-p)) + d^2)
```
