### ISSUE TITLE
Unclear error messages in convert_es()

### ISSUE THREAD

**Issue by pederisager** [psychmeta/psychmeta#51]
I am attempting to convert an effect size "d" into an effect size "cles" using the covert_es function, like so: 

`psychmeta::convert_es(1, "d", "cles")`

However, this does not seem to work, and I receive an error message I do not fully understand:
_Error in UseMethod(generic = "convert_es", object = x) : 
  no applicable method for 'convert_es' applied to an object of class "q_d_to_cles"
In addition: Warning message:
Group SDs = 1 assumed._ 

The package documentation does not seem to specify which classes "convert_es" has a method for (which I assume means which combinations of input and output has a solution?). Nor can I figure out why the conversion of d to cles is not allowed by the function. Going by the conversion formula offered in [Ruscio 2008](https://pdfs.semanticscholar.org/34b2/94fa2883a3af79fcb2f40f1e7c8288546fcf.pdf), it seems my code above provides all the necessary output to calculate cles = pnorm(d/sqrt(2).

**Comment by jadahlke** [comment]
We just released an update that fixes the bug you encountered - your example should work properly now. You will still get a message indicating that the group SDs were assumed to be 1, but this is just a reminder of the assumptions involved in the conversion and is not indicative of any errors in the the inputs or the computations.

**Comment by pederisager** [comment]
Thank you. I just tested the new version against the results reported in [Ruscio (2008)](http://psycnet.apa.org/fulltext/2008-02525-002.html?casa_token=39DgAm3azuYAAAAA:ntWN44pX8uxypN6OGX2upe8C4hyqxiPZDSL59e0K8ldigEw4okGzfbUuqB1sy7DsQtLLdTynK6JeNHnH5tT4HAWC), using the following line of code:

`convert_es(1.451, "d", "cles")`

A = 0.848, which is identical to the conversion as reported by Ruscio.
