### ISSUE TITLE
psychmeta/metafor compatibility

### ISSUE THREAD

**Issue by JulsRos** [psychmeta/psychmeta#53]
...from the psych methods discussion group:

I'm getting the error 
`Error in as.data.frame.default(x[[i]], optional = TRUE, stringsAsFactors = stringsAsFactors) : 
  cannot coerce class ‘"get_escalc"’ to a data.frame`

from the code:

`library(metafor)`
`library(dplyr)`
`library(psychmeta)`

`mlmeta <- read.csv('multilit_meta_prepost.csv', stringsAsFactors = FALSE)`

`mlmeta <- filter(mlmeta, measure == "WARP_wpm")`

`mlmeta <- mlmeta %>%`
            `mutate(sdp = (sd1i+sd2i)/2)`
`d <- (mlmeta$m2i-mlmeta$m1i)/mlmeta$sdp`

`var_d <- var_d <- (2 * (1 - mlmeta$r) / mlmeta$n) + (d ^ 2 / (2 * mlmeta$n - 2) )`
`n_eff <- adjust_n_d(d, var_d)`

`ma_results <- ma_d(d = d, n1 = mlmeta$n, n2 = mlmeta$n, n_adj = 2*n_eff)`
`ma_results$meta_tables`

`es <- get_metafor(ma_results)`
`smd.rma<-rma(yi,vi,method="REML",data=es)`

**Comment by bwiernik** [comment]
As responded to via email:

The structure of the output from get_metafor is a list with a slot for each different meta-analysis you've run (just one entry in this case), with each entry being a list with three slots—one for barebones (uncorrected) analyses, one for individually-corrected analyses, and one for artifact distribution-corrected analyses. To get a data.frame to pass to metafor::rma(), you need to specify which set of variables you want AND which type of corrections for unreliability and range restriction/selection effects (barebones [none], individual-correction, artifact-distribution). For example:
es[[1]]$barebones
