### ISSUE TITLE
construct_order not working

### ISSUE THREAD

**Issue by bwiernik** [psychmeta/psychmeta#72]
Several different odd behaviors (e.g., with `data_r_meas_multi` and with Big Five intercorrelation analyses). Will post some reprex.

**Comment by Clara1912** [comment]
Hi! I just wanted to ask whether this bug was resolved? I ask since I still get the error "No valid construct combinations provided" when I use this function. 
Thanks a lot, best, Clara

**Comment by bwiernik** [comment]
Can you post a reproducible example?

**Comment by Clara1912** [comment]
Hi Brenton,
this is what my code looks like: 
m_bb <- ma_r(data = meta, rxyi = Rxy, n = N,
  sample_id = Art,
  citekey = Short,
  ma_method = "bb",
  construct_x = Construct_x,
  construct_y = Criterion_analysis, 
  construct_order = c("construct 1", "construct 2", "construct 3")
)
The code works fine until I add the construct_order function. Do you have any idea why that is?

**Comment by bwiernik** [comment]
What are the values in your Construct_x and Criterion_analysis columns? Note that construct_order needs to include all of the contructs across both columns that should be included in analyses.
