### ISSUE TITLE
Error loading package

### ISSUE THREAD

**Issue by pdownes** [psychmeta/psychmeta#74]
I can't load 2.3.3 with the following error:

> Error: package or namespace load failed for ‘psychmeta’:
>  .onAttach failed in attachNamespace() for 'psychmeta', details:
>   call: open.connection(x, "rb")
>   error: HTTP error 404.

I think the issue is in zzz.R when the package checks if the local version is up-to-date. I turned off my wifi and was able to load. As best as I can tell, the "www" in line 12 is causing the problem; the link should now be http://r-pkg.org/badges/version/psychmeta. Figured one of you guys could verify better than I!

**Comment by bwiernik** [comment]
Thanks. Should be fixed in the new-released version.

**Comment by ammirsm** [comment]
```
-----------------------------------------------------  psychmeta version 2.3.6  --

Please report any bugs to github.com/psychmeta/psychmeta/issues
or issues@psychmeta.com

We work hard to produce these open-source tools for the R community.
Please cite psychmeta when you use it in your research:
  Dahlke, J. A., & Wiernik, B. M. (2019). psychmeta: An R package for
     psychometric meta-analysis. Applied Psychological Measurement, 43(5),
     415<U+2013>416. https://doi.org/10.1177/0146621618795933

Find info about psychmeta on the web at psychmeta.com and twitter.com/psychmetaR
Error: package or namespace load failed for 'psychmeta':
 .onAttach failed in attachNamespace() for 'psychmeta', details:
  call: stringr::str_split(cran_v_char, "[.]")[[1]]
  error: subscript out of bounds
```

I got this error again on 2.3.6.
